FROM node:18-alpine AS build

WORKDIR /app

COPY package.json ./

RUN npm install

RUN npm run build || tail -n 20 /root/.npm/_logs/*

COPY . .

FROM nginx:1.24.0-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
