version: "3.8"

services:
  api:
    image: inventory-api-staging
    build:
      context: ./backend
      dockerfile: Dockerfile.staging
    container_name: api-staging
    volumes:
      - ./frontend/package.json:/usr/src/app/frontend/package.json
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env.staging
    environment:
      HOST: ${HOST:-0.0.0.0}

  app:
    image: inventory-app-staging
    build:
      context: ./frontend 
      dockerfile: Dockerfile.staging
    container_name: app-staging
    ports:
      - 3000:80
    env_file:
      - ./frontend/.env.staging
