version: '3.8'

services:
  frontend:
    image: liveir/stockpilot-frontend:v1.0.0
    container_name: forntendstockpilot
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=backend:8000
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: liveir/stockpilot-backend:v1.0.0
    container_name: backendstockpilot
    ports:
      - "8000:8000"
    environment:
      - MONGODB_CONNECTION_STRING=mongodb+srv://apacada:6RdKDbxhYUgFGDTK@cluster0.tjvylsn.mongodb.net/stockpilot?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET_KEY=BZT8Y8W3afoqSPQLGEOncVorkapJw2X9 
      - NODE_ENV=development
      - FRONTEND_URL=frontend:8080
    networks:
      - app_network

networks:
  app_network:



  version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  api: 
    build: ./api
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CRUD_DB
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    
volumes:
  mongodb-data:
