import mongoose, { Schema, Document } from 'mongoose';

export type DeploymentHistory = {
  deploymentDate: Date;
  recoveryDate?: Date;
  assignee: string;
}
export interface AssetType extends Document {
  _id: string;
  created: Date;
  createdBy: string;
  updated: Date;
  updatedBy: string;
  type: "Hardware" | "Software";
  code: string;
  brand: string;
  modelName: string;
  modelNo: string;
  serialNo: string;
  category: string;
  status: string;
  remarks: string;
  notifyRemarks: boolean,
  deploymentDate: Date;
  recoveredFrom: string;
  recoveryDate: Date;
  assignee: string;
  deploymentHistory: DeploymentHistory[];
  purchaseDate: Date;
}

/**
 * @openapi
 * components:
 *  schemas:
 *    Asset:
 *      type: object
 *      required:
 *        - code
 *        - type
 *        - dateAdded
 *      properties:
 *        _id:
 *          type: string
 *          example: 01972cf9-c3c7-48c9-8628-ef6148d09c96
 *          description: Auto-generated by MongoDB/Mongoose
 *        code:
 *          type: string
 *          example: FS-XYZ-A
 *        type:
 *          type: string
 *          enum: [Hardware, Software]
 *          example: Hardware
 *        brand:
 *          type: string
 *          example: Apple
 *        modelName:
 *          type: string
 *          example: MacBook Air M2 (2022)
 *        modelNo:
 *          type: string
 *          example: A2681
 *        serialNo:
 *          type: string
 *          example: GD5KD-7GNCB-2TCR0-AX9Z2-KCA6J
 *        created:
 *          type: string
 *          format: date-time
 *          example: "2024-03-14T00:00:00.000Z"
 *        updated:
 *          type: string
 *          format: date-time
 *          example: "2024-03-14T00:00:00.000Z"
 */
const assetSchema: Schema<AssetType> = new Schema<AssetType>({
  created: { type: Date, required: true },
  createdBy: { type: String, required: false},
  updated: { type: Date, required: true },
  updatedBy: { type: String, required: false},
  code: { type: String, required: true, unique: true },
  type: { type: String, enum: ["Hardware", "Software"], required: true },
  brand: { type: String, required: false },
  modelName: { type: String, required: false },
  modelNo: { type: String, required: false },
  serialNo: { type: String, required: false },
  status: { type: String, required: true },
  category: { type: String, required: true },
  remarks: { type: String, required: false },
  notifyRemarks: { type: Boolean, required: false },
  deploymentDate: { type: Date, required: false },
  recoveredFrom: { type: String, required: false },
  recoveryDate: { type: Date, required: false },
  purchaseDate: {type: Date, required: false},
  assignee: {type: String, required: false},
  deploymentHistory: { 
    type: [{
      deploymentDate: { type: Date, required: false },
      recoveryDate: { type: Date, required: false},
      assignee: { type: String, required: true },
    }],
    required: false },
});

const Asset = mongoose.model<AssetType>("Asset", assetSchema);

export default Asset;
