import mongoose, { Schema } from "mongoose";

export type AssetsHistory = {
  deploymentDate: Date;
  recoveryDate: Date;
  assetCode: string;
};

export interface EmployeeType {
  _id: string;
  code: string;
  first_name: string;
  middle_name?: string;
  last_name: string;
  position: string;
  startDate: Date;
  isActive: boolean;
  isRegistered: boolean;
  assetsHistory: AssetsHistory[];
}

/**
 * @openapi
 * components:
 *  schemas:
 *    Employee:
 *      type: object
 *      required:
 *        - first_name
 *        - middle_name
 *        - last_name
 *        - position
 *        - startDate
 *      properties:
 *        _id:
 *          type: string
 *          example: b40f7c8b-acf7-4101-8010-276d5eb07760
 *          description: Auto-generated by MongoDB/Mongoose
 *        first_name:
 *          type: string
 *          example: John
 *        middle_name:
 *          type: string
 *          example: Smith
 *        last_name:
 *          type: string
 *          example: Doe
 *        position:
 *          type: string
 *          example: Developer
 *        startDate:
 *          type: string
 *          format: date-time
 *          example: "2024-03-14T00:00:00.000Z"
 *        isRegistered:
 *          type: boolean
 *          description: If employee was registered to the system or not.
 *        assetsHistory:
 *          type: array
 *          items:
 *            type: object
 *            properties:
 *              deploymentDate:
 *                type: Date
 *              recoveryDate:
 *                type: Date
 *              assetCode:
 *                type: String
 *          description: History of assets deployed to this employee
 */
const employeeSchema: Schema<EmployeeType> = new mongoose.Schema<EmployeeType>({
  code: { type: String, required: true, unique: true },
  first_name: { type: String, required: true },
  middle_name: { type: String, required: false },
  last_name: { type: String, required: true },
  position: { type: String, required: true },
  startDate: { type: Date, required: true },
  isActive: { type: Boolean, required: true },
  isRegistered: { type: Boolean, required: true },
  assetsHistory: {
    type: [
      {
        deploymentDate: { type: Date, required: true },
        recoveryDate: { type: Date, required: true },
        assetCode: { type: String, required: true },
      },
    ],
    required: false,
  },
});

const Employee = mongoose.model<EmployeeType>("Employee", employeeSchema);

export default Employee;
