name: Build Frontend

on:
  pull_request:
    branches:
      - 'staging'
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        working-directory: './frontend'
      - run: npm run build
        working-directory: './frontend'
      - run: npm ci
        working-directory: './backend'
      - run: npm run build
        working-directory: './backend'