name: Pull Request CI/CD

on:
  pull_request:
    branches:
      - develop
      - feature/*
      - bugfix/*
      - fix/*
      - improvement/*

permissions:
  id-token: write
  contents: read

jobs:
  authentication:
    name: Authentication Setup
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: authentication
    environment: develop

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Push Frontend
        working-directory: ./frontend
        run: |
          docker build -t ${{ secrets.ACR_USERNAME }}.azurecr.io/app:pr-${{ github.event.number }} .
          docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/app:pr-${{ github.event.number }}

      - name: Build and Push Backend
        working-directory: ./backend
        run: |
          docker build -t ${{ secrets.ACR_USERNAME }}.azurecr.io/api:pr-${{ github.event.number }} .
          docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/api:pr-${{ github.event.number }}

  deploy:
    name: Deploy to Azure App Services
    needs: build-and-push-images
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Deploy Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: pr-${{ github.event.number }}-api
          images: ${{ secrets.ACR_USERNAME }}.azurecr.io/api:pr-${{ github.event.number }}

      - name: Deploy Frontend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: pr-${{ github.event.number }}
          images: ${{ secrets.ACR_USERNAME }}.azurecr.io/frontend:pr-${{ github.event.number }}
