# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - staging-fullscale-inventory

on:
  push:
    branches:
      - improvement/mern-setup
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build Application
        run: |
          ls -lstra
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: staging-fullscale-inventory
    
    steps:      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: staging-fullscale-inventory
          slot-name: Production
          package: .
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}

      - name: Start application
        run: |
          ls -lstra
          ls -lstra frontend
          ls -lstra frontend
          npm run start
  