# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - production-fullscale-inventory

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install and build the React frontend
      # using npm run start, since the existing package.json 
      # uses npm run start to build a NODE_ENV for production
      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run start

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Build backend if using TypeScript
      - name: Build backend (TypeScript)
        run: |
          cd backend
          npm run build
      
      # Zip backend and reference the React 'dist' directory
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./backend ./frontend/dist

      # Upload the artifact for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FCBC7F6913CB44C197BF6D462741B885 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9978C6DD43BE49EEA4043371B47AC42F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC34528593824BF3817FFD3D40DC0B3A }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'production-fullscale-inventory'
          slot-name: 'Production'
          package: .
          